### PR TITLE
Fix: Recover does not pin recursively

### PR DESCRIPTION
**Pull request by hsanjuan**
First bug from testing 0.3.5-rc1 (good that I did an rc).

@ZenGround0 the pin tracker will need some changes with sharding... probably should carry the pin types of the tracked things.

### CODE REVIEW

**Comment by hsanjuan** [comment]
@ZenGround0 will storing the pinType in the tracker be enough ?

**Comment by ZenGround0** [comment]
No not alone because as it stands validation checks in the `pin` function would raise complaints that the right fields are not set.  We could make changes to the pin function to accommodate this however.

**Comment by hsanjuan** [comment]
@ZenGround0 but the tracker is not involved in those checks, it only needs to tell the ipfs connector how to pin something?

**Comment by ZenGround0** [comment]
Oh, thank you.  I was mixing up repin-from-peer and the pin tracker repinning on ipfs

**Pull request merged**
