### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by hsanjuan**
@lgierth @Kubuxu would appreciate if you have a look to this and tell me if I'm doing something wrong, since I'm not much into docker. I have copied from ipfs as much as I could... (and works for me)

### CODE REVIEW

**Comment by brainstorm** [comment]
Works like a charm for me:

```
$ docker run -it a0331d6eaeef /bin/bash
ipfs version 0.4.6
initializing IPFS node at /data/ipfs
generating 2048-bit RSA keypair...done
peer identity: QmXe1jf4upWRUPN3K66ZaMZpm6MfCfhWTwc1CbEtHStEYz
to get started, enter:

	ipfs cat /ipfs/QmVLDAhCY3X9P2uRudKAryuQFPM5zqA3Yij1dY8FpGbL7T/readme

Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/172.17.0.2/tcp/4001
Swarm listening on /ip4/83.251.116.207/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
API server listening on /ip4/0.0.0.0/tcp/5001
Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080
Daemon is ready
ipfs-cluster-service version 0.0.4
18:06:20.076  INFO    cluster: Saving configuration config.go:320
ipfs-cluster-service configuration written to /data/ipfs-cluster/service.json
18:06:20.089  INFO    cluster: IPFS Cluster v0.0.4 listening on: cluster.go:76
18:06:20.089  INFO    cluster:         /ip4/127.0.0.1/tcp/9096/ipfs/Qmd4SMmMjNq2HA3LM4HYKHpxX8wLeKiKCBdFnEwmJQrgVV cluster.go:78
18:06:20.089  INFO    cluster:         /ip4/172.17.0.2/tcp/9096/ipfs/Qmd4SMmMjNq2HA3LM4HYKHpxX8wLeKiKCBdFnEwmJQrgVV cluster.go:78
18:06:20.090  INFO    cluster: starting Consensus and waiting for a leader... consensus.go:57
18:06:20.100  INFO    cluster: IPFS Proxy: /ip4/0.0.0.0/tcp/9095 -> /ip4/127.0.0.1/tcp/5001 ipfs_http_connector.go:170
18:06:20.100  INFO    cluster: REST API: /ip4/0.0.0.0/tcp/9094 rest_api.go:225
18:06:20.100  INFO    cluster: waiting for leader raft.go:118
18:06:21.349  INFO    cluster: Raft Leader elected: Qmd4SMmMjNq2HA3LM4HYKHpxX8wLeKiKCBdFnEwmJQrgVV raft.go:145
18:06:21.349  INFO    cluster: Consensus state is up to date consensus.go:107
18:06:21.350  INFO    cluster: Cluster Peers (not including ourselves): cluster.go:327
18:06:21.350  INFO    cluster:     - No other peers cluster.go:330
18:06:21.350  INFO    cluster: IPFS Cluster is ready cluster.go:336
```

Coincidentally I was putting together an ansible role to deploy ipfs-cluster:

https://github.com/brainstorm/ansible-ipfs-cluster

But I like your approach much better @hsanjuan ! ;)

**Comment by hsanjuan** [comment]
@brainstorm I do have an ansible role myself (which rolls ipfs+ipfs-cluster on my raspberries Pis).. you should keep it around as there's always people that find it useful. I was thinking of sharing mine too.

Also, I have ipfs-cluster builds coming up in dist.ipfs.io so it will be easier to just download and unarchive from there.

**Comment by brainstorm** [comment]
Please @hsanjuan, do share yours, I was having some silly issues with golang roles on mine which I bet you've solved well in your role(s). Happy to tweak/generalize your roles for y(our) needs :)

**Comment by brainstorm** [comment]
@hsanjuan For distribution of `ipfs-cluster` it would be super handy if it were distributed via ipfs's dockerhub:

https://hub.docker.com/r/ipfs/

That way I can just plug in the uploaded docker image into my docker-compose:

https://github.com/ga4gh/cgtd/blob/docker-compose/docker-compose.yml

For now I'll just upload it on my project or personal dockerhub account, but it would be super convenient to have it up there through the official docker/dockerhub channels.

**Comment by hsanjuan** [comment]
@brainstorm agreed!

**Comment by hsanjuan** [comment]
@brainstorm https://github.com/hsanjuan/ansible-ipfs-cluster in case you're interested.

**Pull request merged**
