### PR TITLE
Documentation: Can't get peers to connect without /ipfs/ before <id>.

### PR DESCRIPTION
**Pull request by racin**
This is also reflected in the other documentations.

License: MIT
Signed-off-by: racin

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 35bfdd7db9fbd2403b7e3b5bdf57c8bc9a9eb0e9
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

Guidelines are available at https://github.com/ipfs/ipfs-cluster/blob/master/contribute.md

---
This message was auto-generated by https://gitcop.com

**Comment by hsanjuan** [comment]
@racin, can you fix the commit message (see gitcop comment).

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 35bfdd7db9fbd2403b7e3b5bdf57c8bc9a9eb0e9
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

Guidelines are available at https://github.com/ipfs/ipfs-cluster/blob/master/contribute.md

---
This message was auto-generated by https://gitcop.com

**Comment by hsanjuan** [comment]
good enough for me, thanks :)

**Pull request merged**
