### PR TITLE
Move `ipfs-cluster-service` and `ipfs-cluster-ctl` to `cmd/`

### LINKED ISSUE #485: Move `ipfs-cluster-service` and `ipfs-cluster-ctl` to `cmd/`
#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Master
  * [ ] Release candidate for next version
  * [ ] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [ ] Bug
  * [x] Feature request
  * [ ] Enhancement

#### Description
Move `ipfs-cluster-service` and `ipfs-cluster-ctl` to `cmd/` directory to follow "standard" project structure.

### PR DESCRIPTION
**Pull request by kishansagathiya**
This PR moves `ipfs-cluster-service` and `ipfs-cluster-ctl` to
`cmd/` directory to follow "standard" project structure.

Fixes #485

### CODE REVIEW

**Comment by hsanjuan** [comment]
@kishansagathiya can you rebase this in master? This merge is half blocked because I think it might break the `ipfs/distributions` builds and I need to check that (and have time to fix it the moment this is merged).

**Comment by kishansagathiya** [comment]
@hsanjuan Conflicts are resolved.

**Comment by hsanjuan** [comment]
@kishansagathiya still some conflicts here..

**Comment by hsanjuan** [comment]
I have rebased this in #556 and will merge from there

**Pull request closed without merging**
