### PR TITLE
Add the instructions to install the snap

### PR DESCRIPTION
**Pull request by elopio**
I have just pushed an initial version of ipfs-cluster to the snapcraft store:
https://discuss.ipfs.io/t/start-testing-the-ipfs-cluster-snap/1422

### CODE REVIEW

**Comment by elopio** [comment]
@hsanjuan done! :)

**Comment by elopio** [comment]
Thank you! I'm getting an updated cluster every night, so if you want me to help you trying something new just say the word.

**Comment by hsanjuan** [comment]
Thanks, are you running it or just building?

**Comment by elopio** [comment]
I am not building it, [travis builds it for me every night](https://github.com/elopio/ipfs-cluster/blob/dca9eb77310d658c23ce61006215499cc448145f/.travis.yml#L37). Then a few times a week I'm running it, but only a smoke test to check if the package is sane. I don't have a real use case yet, to test it in production.

**Comment by hsanjuan** [comment]
Hey @elopio , why don't we just add the snapcraft.yaml to the official repo and build the snaps directly from here ? I think this will give a more official status to this packaging and we can track any necessary a bit better.

**Pull request merged**
