### PR TITLE
Adding Jenkinsfile -- Experiment

### PR DESCRIPTION
**Pull request by ZenGround0**
Let's see what happens.

### CODE REVIEW

**Comment by hsanjuan** [comment]
Wow did jenkins appear out of the blue with just that ?

**Comment by ZenGround0** [comment]
@hsanjuan yeah this is like magic

Yup my thoughts too.  We might be able to request a custom jenkinsfile like go-ipfs, or perhaps implement the general makefile interface if that idea becomes reality.

**Comment by VictorBjelkholm** [comment]
> yeah this is like magic

Hurrah! That's the feeling I went for (good magic, not bad magic where you don't know what's happening) so happy to see :)

> Yup my thoughts too. We might be able to request a custom jenkinsfile like go-ipfs, or perhaps implement the general makefile interface if that idea becomes reality.

Let's think carefully about this, as I would much rather prefer standarization and a unified way of executing tests, installs dependencies and such (which also contributors would prefer). Opened a issue for it here: https://github.com/ipfs/community/issues/276

Please leave any feedback so we hopefully can realize that idea.

**Comment by VictorBjelkholm** [comment]
Just noticed that the test run for ipfs-cluster outputted 4GB of logs, that might slightly too much (but not a problem for Travis apparently)

**Comment by VictorBjelkholm** [comment]
I turned off verbose logging for golang tests (https://github.com/victorbjelkholm/jenkins-libs/commit/fb7e28d29296f5899fd614a989441bfd70d7759d), but `go test ./...` still seems to spit out a lot of logs.

**Comment by hsanjuan** [comment]
heheh... yeah that's why we need to run with `go test -v -tags silent ./...` @VictorBjelkholm . 4GB seems a bit too much though, but maybe is consistent with tests which start 6 cluster peers and do some thousands of pins.

**Comment by hsanjuan** [comment]
Is there a way to tell jenkins to run `make test` or a custom script for that matter @VictorBjelkholm ?

**Comment by VictorBjelkholm** [comment]
@hsanjuan just implemented that and running builds with `go test -tags silent -v ./...` for ipfs-cluster now.

**Comment by VictorBjelkholm** [comment]
For linux and macOS, I can only see one test failure:

```
=== RUN   TestClustersSyncLocal
*** Test killed: ran too long (10m0s).
FAIL	github.com/ipfs/ipfs-cluster	605.004s
```

On windows there is bunch of failures. See https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fipfs-cluster/detail/PR-256/4/pipeline/8

Let me know if there is anything else you need from Jenkins side of this. Otherwise this is ready to be merged

**Comment by ZenGround0** [comment]
@VictorBjelkholm Thanks!  One thing that seems to be missing that we'll eventually want is sharness testing.  Does Jenkins support makefile invocations?

**Comment by VictorBjelkholm** [comment]
If they are being run the same way as go-ipfs, it'll be easy to have for ipfs-cluster as well. If not, have to figure out a way to easily add custom commands to run after the default ones.

**Comment by hsanjuan** [comment]
I guess I need to login to retrigger things ?

**Comment by VictorBjelkholm** [comment]
@hsanjuan yes, jenkins uses the permissions from Github

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: efd3863e6c19f8887c82028103a42a781de4d882
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

 * Commit: e7384e3bb28bc26823ba758c81f0e773af715869
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

Guidelines are available at https://github.com/ipfs/ipfs-cluster/blob/master/contribute.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: efd3863e6c19f8887c82028103a42a781de4d882
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

 * Commit: e7384e3bb28bc26823ba758c81f0e773af715869
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

Guidelines are available at https://github.com/ipfs/ipfs-cluster/blob/master/contribute.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: efd3863e6c19f8887c82028103a42a781de4d882
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

 * Commit: e7384e3bb28bc26823ba758c81f0e773af715869
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

Guidelines are available at https://github.com/ipfs/ipfs-cluster/blob/master/contribute.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: efd3863e6c19f8887c82028103a42a781de4d882
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

 * Commit: e7384e3bb28bc26823ba758c81f0e773af715869
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

Guidelines are available at https://github.com/ipfs/ipfs-cluster/blob/master/contribute.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: efd3863e6c19f8887c82028103a42a781de4d882
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

 * Commit: e7384e3bb28bc26823ba758c81f0e773af715869
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

Guidelines are available at https://github.com/ipfs/ipfs-cluster/blob/master/contribute.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: efd3863e6c19f8887c82028103a42a781de4d882
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

 * Commit: e7384e3bb28bc26823ba758c81f0e773af715869
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

Guidelines are available at https://github.com/ipfs/ipfs-cluster/blob/master/contribute.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 5eb918de5eb14911b30899eea1096223458e0dfe
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

Guidelines are available at https://github.com/ipfs/ipfs-cluster/blob/master/contribute.md

---
This message was auto-generated by https://gitcop.com

**Comment by VictorBjelkholm** [comment]
@gitcop and @coveralls are a bit annoying, might consider putting those as commit statuses rather than comments in the PR.

@hsanjuan I've updated the format of the jenkinsfile, as it gets a map passed into it now. Seems it's only testing the consensus right now, but everything is passing on all platforms now.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 5eb918de5eb14911b30899eea1096223458e0dfe
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

Guidelines are available at https://github.com/ipfs/ipfs-cluster/blob/master/contribute.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 5eb918de5eb14911b30899eea1096223458e0dfe
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

Guidelines are available at https://github.com/ipfs/ipfs-cluster/blob/master/contribute.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 5eb918de5eb14911b30899eea1096223458e0dfe
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

Guidelines are available at https://github.com/ipfs/ipfs-cluster/blob/master/contribute.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 5eb918de5eb14911b30899eea1096223458e0dfe
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

Guidelines are available at https://github.com/ipfs/ipfs-cluster/blob/master/contribute.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 5eb918de5eb14911b30899eea1096223458e0dfe
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

Guidelines are available at https://github.com/ipfs/ipfs-cluster/blob/master/contribute.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 5eb918de5eb14911b30899eea1096223458e0dfe
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

Guidelines are available at https://github.com/ipfs/ipfs-cluster/blob/master/contribute.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4bd2e2f8c10340c09de3bce75b80d0d6304aa6cb
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

Guidelines are available at https://github.com/ipfs/ipfs-cluster/blob/master/contribute.md

---
This message was auto-generated by https://gitcop.com

**Comment by hsanjuan** [comment]
@ZenGround0 So I'd like to merge this. linux build passes sometime. There is something deeper than cluster going on (heisenbugs at the libp2p level). Mac fails almost aways and Windows.... let's not speak of windows. We can keep jenkins as an additional source of information for the moment.

We can address those issues when we have time and hours to do it.

**Comment by hsanjuan** [comment]
@ZenGround0 since it's your PR I cannot set you as reviewer, let me know if things look good or not though.

**Comment by VictorBjelkholm** [comment]
@ZenGround0 

The only advice I can come up with is to make sure you're using `0` everywhere when setting up listeners, as then it's impossible to have any conflicts.

Regarding the osx/windows failures, try getting some developer who is using osx/windows as their main developer machine to run the tests and compare with jenkins. If it's just failing on jenkins, I can start digging into it more.

**Comment by hsanjuan** [comment]
@VictorBjelkholm it needs to bring up containers etc to run sharness

**Comment by hsanjuan** [comment]
@ZenGround0 those failures come from windows I think. The OS has trouble releasing ports for re-use. Using port 0 as @VictorBjelkholm suggests is one approach to maybe fix things, but I'm gonna save it for the next round.

**Comment by VictorBjelkholm** [comment]
> it needs to bring up containers etc to run sharness

Yeah, linux workers have Docker already (which I assume you're using for the containers) so as long as you use `node(label: 'linux') { /* run sharness here */ }`, you should be fine

**Comment by hsanjuan** [comment]
@VictorBjelkholm where should we use that? in the jenkins file in a new line or how ?

**Pull request merged**
