### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by lanzafame**
Link to "How to Build and Update a Cluster" was broken.

License: MIT
Signed-off-by: Adrian Lanzafame <adrian.lanzafame@protocol.ai>

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e8e9b349f50dfe32386913aa86c7633eb3537cdb
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

Guidelines are available at https://github.com/ipfs/ipfs-cluster/blob/master/contribute.md

---
This message was auto-generated by https://gitcop.com

**Comment by lanzafame** [comment]
@hsanjuan Not sure why GitCop is yelling at me? I did do this PR from the GitHub website but I didn't think that would change anything.

**Comment by ZenGround0** [comment]
GitCop shouldn't be doing this.  This PR LGTM

**Comment by hsanjuan** [comment]
I'm not sure about Gitcop :/

But THANKS

**Pull request merged**
