### PR TITLE
Adder: try to make test less flaky

### LINKED ISSUE #1461: TestAdder_ContextCancelled seems to be flaky
**Additional information:**
 - OS: Linux (NixOS)
 - IPFS Cluster version: 0.14.1
 - Installation method: built from source

**Describe the bug:**

I tried updating the version of ipfs-cluster in Nixpkgs from 0.14.0 to 0.14.1: https://github.com/NixOS/nixpkgs/pull/134342. A bot built the new version and ran the test suite but the test TestAdder_ContextCancelled failed. The logs are in https://gist.github.com/r-rmcgibbo/4120129668b85b2bc51dc6f70c64b651. The bot built ipfs-cluster twice, for two different architectures and it failed once. I also can't reproduce the failure on any of my machines, so the failure seems to be non-deterministic. I noticed, that it failed before in https://github.com/ipfs/ipfs-cluster/pull/613#issue-235170657.

### PR DESCRIPTION
**Pull request by hsanjuan**
Fixes #1461

### CODE REVIEW

**Comment by Luflosi** [comment]
Instead of making it "less flaky", would it be possible to make it absolutely 100% reliable?

**Comment by hsanjuan** [comment]
Everything is possible. But I don't have time for everything so I'm happy with the 99.9%.

**Comment by Luflosi** [comment]
You should update the comment as well.

**Review by AMRo-Crypto — APPROVED** [review]

**Comment by AMRo-Crypto** [comment]
- nice

**Pull request merged**
