### PR TITLE
Feat/recursive pins

### PR DESCRIPTION
**Pull request by ZenGround0**
@hsanjuan the second half of the proposal in #325, this time with a migration from state format 3 to 4 and merging into master.

### CODE REVIEW

**Comment by ZenGround0** [comment]
@hsanjuan Travis passes now

**Comment by hsanjuan** [comment]
@ZenGround0 nope:

```
./cluster_test.go:106:23: cannot use ipfs (type *mockConnector) as type IPFSConnector in argument to NewCluster:
	*mockConnector does not implement IPFSConnector (wrong type for Pin method)
		have Pin(*cid.Cid) error
		want Pin(*cid.Cid, bool) error
FAIL	github.com/ipfs/ipfs-cluster [build failed]
```

it's because travis doesn't detect failures

**Comment by ZenGround0** [comment]
@hsanjuan Now this should be good to go, though one of the travis runs fails on the unrelated buggy test "PeerRemoveSelf".

**Comment by hsanjuan** [comment]
I have retriggered the tests, will wait until they pass

**Pull request merged**
