### PR TITLE
A guide to running ipfs cluster

### PR DESCRIPTION
**Pull request by hsanjuan**
This should fix what I meant in #84

License: MIT
Signed-off-by: Hector Sanjuan <hector@protocol.ai>

### CODE REVIEW

**Comment by hsanjuan** [comment]
Would be good to get feedback here.

@bgadmin, would you like to read this guide and provide some feedback? Like things that are missing, or not clear enough and can be better explained...

**Comment by bgadmin** [comment]
@hsanjuan sure thing, sorry for late reply will get back to you today :)

**Comment by VictorBjelkholm** [comment]
Would be nice to have a quickstart in the top, similar to what was in the top-level readme.md before, where you just list the minimal set of commands to get up and running.

**Comment by hsanjuan** [comment]
I have added the quickstart to the main README.. The guide is meant for a more in-depth approach.

**Pull request merged**
