### PR TITLE
Copyedit in README

### PR DESCRIPTION
**Pull request by meiqimichelle**
There was a slight grammar mistake. Now it is gone, and this sentence matches the one on our website.

I submitted this PR yesterday, but it wasn't signed properly. I'm opening a new PR to test where the signature should go in the GH web interface (clearly did not have it in the right place last time).

License: MIT
Signed-off-by: Michelle Hertzfeld mhertzfeld@gmail.com

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 89cd4b83bfbd96e3e919c9636c88de273bfa669f
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

Code contribution guidelines for IPFS Cluster are available at https://cluster.ipfs.io/developer/contribute/#code-contribution-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by meiqimichelle** [comment]
That's interesting. So, I think there's no way to sign commits in the GH web interface. At least when you don't have commit access to the repo. (Would want to test the other case, too, when someone *does* have access.)

Boo.

**Comment by hsanjuan** [comment]
Probably an issue in the regexp matching in gitcop :( You'd probably enjoy doing it in the command line at this point though. I'll give you write access too.

**Comment by meiqimichelle** [comment]
Ah, I see re: gitcop. Yeah, I don't mind command line. I just tend to notice wording/grammar improvements when I'm reading on the website, and it's easy to click the button from there (or on mobile). Thx for merging for now, and thx for write access!

**Pull request merged**
