### PR TITLE
update build status link in README

### PR DESCRIPTION
**Pull request by roignpar**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 851d626ff3905e99325f3e81b2b2bac4f6cebba0
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by:**

Code contribution guidelines for IPFS Cluster are available at https://cluster.ipfs.io/developer/contribute/#code-contribution-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by roignpar** [comment]
will open a new PR with the correct commit message

**Comment by hsanjuan** [comment]
@roignpar my tip is you check `git commit --amend` and `git rebase -i master`.

**Comment by roignpar** [comment]
I made the changes directly on github, without cloning locally. That's why it was faster for me to open a new PR: #662. GitCop is still complaining, even though I made the changes it mentioned. I can't tell if something else is wrong with the commit message since I can't access the contribution guide link.

If you prefer I can rename this commit.

**Comment by hsanjuan** [comment]
No. it's ok. Merged the other.

**Pull request closed without merging**
